baseURL = "https://than22012004.github.io/FCAJ-WorkShop/"
languageCode = "vi"
title = "Báo cáo thực tập"

theme = "hugo-theme-learn"

defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false

relativeURLs = false
canonifyURLs = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "workshop"
editURL = ""
description = ""
author = "thanpham2k4@gmail.com"
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false

[languages]

[languages.en]
title = "Internship Report"
weight = 1
label = "English"

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 30

[languages.vi]
title = "Báo cáo thực tập"
weight = 2
label = "Tiếng Việt"

[[languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true